language: node_js
node_js:
  - '6'
cache:
  bundler: true
  directories:
  - node_modules # NPM package
notifications:
  email: false
script: npm run cover
after_success: cat /home/travis/build/glayzzle/hack-parser/coverage/lcov.info | /home/travis/build/glayzzle/hack-parser/node_modules/coveralls/bin/coveralls.js
